# Generated by Django 4.0.6 on 2022-07-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('Address', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_Number', models.CharField(max_length=12)),
                ('Gender', models.CharField(max_length=7)),
                ('nationality', models.CharField(max_length=15)),
                ('Age', models.IntegerField()),
            ],
        ),
    ]
