# Generated by Django 4.0.6 on 2022-08-19 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipts',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='receipt',
        ),
    ]
