# Generated by Django 4.0.6 on 2022-08-19 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_remove_receipts_transaction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipts',
            old_name='recipt_File',
            new_name='receipt_File',
        ),
        migrations.RenameField(
            model_name='receipts',
            old_name='recipt_number',
            new_name='receipt_number',
        ),
    ]
